In [141]:
import pandas as pd
import numpy as np

In [142]:
df = pd.read_csv("Credit_Score_Clean.csv")
df.head(5)

,Age,Occupation,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Credit_History_Age_Months
0,23,Scientist,19114.12,3,4,3,4,5,4,6.27,...,Good,809.98,31.377862,No,49.574949,199.458074,Low_spent_Small_value_payments,223.451310,Good,268
1,23,Scientist,19114.12,3,4,3,4,6,0,11.27,...,Good,809.98,24.797347,No,49.574949,41.420153,High_spent_Medium_value_payments,341.489231,Good,269
2,23,Scientist,19114.12,3,4,3,4,3,8,11.27,...,Good,809.98,22.537593,No,49.574949,178.344067,Low_spent_Small_value_payments,244.565317,Good,271
3,23,Scientist,19114.12,3,4,3,4,3,6,11.27,...,Good,809.98,23.933795,No,49.574949,24.785217,High_spent_Medium_value_payments,358.124168,Standard,0
4,28,Teacher,34847.84,2,4,6,1,7,1,7.42,...,Good,605.03,38.550848,No,18.816215,40.391238,High_spent_Large_value_payments,484.591214,Good,320

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31711 entries, 0 to 31710
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        31711 non-null  int64
 1   Occupation                 31711 non-null  object
 2   Annual_Income              31711 non-null  float64
 3   Num_Bank_Accounts          31711 non-null  int64
 4   Num_Credit_Card            31711 non-null  int64
 5   Interest_Rate              31711 non-null  int64
 6   Num_of_Loan                31711 non-null  int64
 7   Delay_from_due_date        31711 non-null  int64
 8   Num_of_Delayed_Payment     31711 non-null  int64
 9   Changed_Credit_Limit       31711 non-null  float64
 10  Num_Credit_Inquiries       31711 non-null  float64
 11  Credit_Mix                 31711 non-null  object
 12  Outstanding_Debt           31711 non-null  float64
 13  Credit_Utilization_Ratio   31711 non-null  float64
 14  Payment_of_Min_Amount      31711 non-null  object
 15  Total_EMI_per_month        31711 non-null  float64
 16  Amount_invested_monthly    31711 non-null  float64
 17  Payment_Behaviour          31711 non-null  object
 18  Monthly_Balance            31711 non-null  float64
 19  Credit_Score               31711 non-null  object
 20  Credit_History_Age_Months  31711 non-null  int64
dtypes: float64(8), int64(8), object(5)
memory usage: 5.1+ MB

In [144]:
df.describe(include="object").T

                       count unique                             top   freq
Occupation             31711     15                          Lawyer   2401
Credit_Mix             31711      3                        Standard  17138
Payment_of_Min_Amount  31711      3                              No  16620
Payment_Behaviour      31711      6  Low_spent_Small_value_payments   8301
Credit_Score           31711      3                        Standard  19730

In [145]:
df["Credit_Score"].value_counts()

Credit_Score
Standard    19730
Good         7551
Poor         4430
Name: count, dtype: int64

In [146]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

In [147]:
categories = ["Poor", "Standard", "Good"]
encoder = OrdinalEncoder(categories=[categories])
df["Credit_Score"] = encoder.fit_transform(df[["Credit_Score"]])
df["Credit_Score"] = df["Credit_Score"].astype("int")
df["Credit_Score"].value_counts()

Credit_Score
1    19730
2     7551
0     4430
Name: count, dtype: int64

In [148]:
df["Credit_Mix"].value_counts()

Credit_Mix
Standard    17138
Good        13875
Bad           698
Name: count, dtype: int64

In [149]:
categories = ["Bad", "Standard", "Good"]
encoder = OrdinalEncoder(categories=[categories])
df["Credit_Mix"] = encoder.fit_transform(df[["Credit_Mix"]])
df["Credit_Mix"] = df["Credit_Mix"].astype("int")
df["Credit_Mix"].value_counts()

Credit_Mix
1    17138
2    13875
0      698
Name: count, dtype: int64

In [150]:
df["Payment_of_Min_Amount"].value_counts()

Payment_of_Min_Amount
No     16620
Yes    11267
NM      3824
Name: count, dtype: int64

In [151]:
df["Payment_of_Min_Amount"] = LabelEncoder().fit_transform(df["Payment_of_Min_Amount"])
df["Payment_of_Min_Amount"].value_counts()

Payment_of_Min_Amount
1    16620
2    11267
0     3824
Name: count, dtype: int64

In [152]:
df["Payment_Behaviour"].value_counts()

Payment_Behaviour
Low_spent_Small_value_payments      8301
High_spent_Medium_value_payments    6369
High_spent_Large_value_payments     4848
Low_spent_Medium_value_payments     4592
High_spent_Small_value_payments     3939
Low_spent_Large_value_payments      3662
Name: count, dtype: int64

In [153]:
categories = ["Low_spent_Small_value_payments",
    "Low_spent_Medium_value_payments",
    "Low_spent_Large_value_payments",
    "High_spent_Small_value_payments",
    "High_spent_Medium_value_payments",
    "High_spent_Large_value_payments"
]
encoder = OrdinalEncoder(categories=[categories])
df["Payment_Behaviour"] = encoder.fit_transform(df[["Payment_Behaviour"]])
df["Payment_Behaviour"] = df["Payment_Behaviour"].astype("int")
df["Payment_Behaviour"].value_counts()

Payment_Behaviour
0    8301
4    6369
5    4848
1    4592
3    3939
2    3662
Name: count, dtype: int64

In [154]:
df["Occupation"].value_counts()

Occupation
Lawyer           2401
Architect        2328
Media_Manager    2144
Teacher          2130
Accountant       2111
Developer        2105
Scientist        2102
Musician         2098
Journalist       2093
Entrepreneur     2088
Engineer         2042
Mechanic         2042
Manager          2022
Doctor           2022
Writer           1983
Name: count, dtype: int64

In [155]:
df["Occupation"] = LabelEncoder().fit_transform(df["Occupation"])
df["Occupation"].value_counts()

Occupation
7     2401
1     2328
10    2144
13    2130
0     2111
2     2105
12    2102
11    2098
6     2093
5     2088
4     2042
9     2042
8     2022
3     2022
14    1983
Name: count, dtype: int64

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31711 entries, 0 to 31710
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        31711 non-null  int64
 1   Occupation                 31711 non-null  int64
 2   Annual_Income              31711 non-null  float64
 3   Num_Bank_Accounts          31711 non-null  int64
 4   Num_Credit_Card            31711 non-null  int64
 5   Interest_Rate              31711 non-null  int64
 6   Num_of_Loan                31711 non-null  int64
 7   Delay_from_due_date        31711 non-null  int64
 8   Num_of_Delayed_Payment     31711 non-null  int64
 9   Changed_Credit_Limit       31711 non-null  float64
 10  Num_Credit_Inquiries       31711 non-null  float64
 11  Credit_Mix                 31711 non-null  int64
 12  Outstanding_Debt           31711 non-null  float64
 13  Credit_Utilization_Ratio   31711 non-null  float64
 14  Payment_of_Min_Amount      31711 non-null  int64
 15  Total_EMI_per_month        31711 non-null  float64
 16  Amount_invested_monthly    31711 non-null  float64
 17  Payment_Behaviour          31711 non-null  int64
 18  Monthly_Balance            31711 non-null  float64
 19  Credit_Score               31711 non-null  int64
 20  Credit_History_Age_Months  31711 non-null  int64
dtypes: float64(8), int64(13)
memory usage: 5.1 MB

In [157]:
df.sample(5)

,Age,Occupation,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Credit_History_Age_Months
3094,36,0,16341.075,4,4,6,2,8,22,11.63,...,1,684.05,25.796431,1,16.960460,0.000000,0,228.503428,1,201
4193,36,9,107392.740,5,5,6,1,30,23,10.69,...,1,248.84,35.562237,2,51.613897,424.745606,1,671.779997,1,233
19840,48,7,60865.050,5,7,3,3,21,10,3.23,...,1,1188.49,24.987294,1,140.209934,265.375757,2,386.523059,1,295
15531,27,6,44657.680,4,3,2,3,13,5,5.21,...,2,1325.96,40.640384,1,88.801440,112.081189,4,421.664704,2,222
16059,35,8,18550.400,3,4,34,2,17,10,15.08,...,1,1368.63,34.834320,2,28.830800,148.594992,0,278.660875,0,112

In [158]:
X = df.drop(["Credit_Score"], axis=1)
y = df["Credit_Score"]
print(X.shape, y.shape)

(31711, 20) (31711,)

In [159]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

In [160]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [161]:
from sklearn.ensemble import RandomForestClassifier

In [162]:
model = RandomForestClassifier(n_estimators=10, random_state=40, oob_score=True)
model.fit(X_train, y_train)

/home/data02/anaconda3/lib/python3.13/site-packages/sklearn/ensemble/_forest.py:612: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

RandomForestClassifier(n_estimators=10, oob_score=True, random_state=40)

In [163]:
from sklearn.metrics import accuracy_score
oob_score = model.oob_score_
pred = model.predict(X_test)
print(oob_score)
print(accuracy_score(y_test, pred))

0.711802270577105
0.7491723159388302

In [198]:
def PSI(pred, actual):
    bins = []
    dev = []
    exp = []
    psi = []
    for i in range(3):
        bins.append(i)
        ctr = 0
        for j in actual:
            if i == j:
                ctr += 1
        dev.append(ctr/len(actual))
        ctr = 0
        for j in pred:
            if i ==j:
                ctr += 1
        exp.append(ctr/len(pred))
        psi.append((dev[i] - exp[i]) * math.log(dev[i] / exp[i]))
    dic = { "bins": bins, "dev": dev, "exp": exp, "psi": psi}
    return sum(dic["psi"])

In [199]:
PSI(model.predict(X_test), y_test)

0.01780781317181853